### ISSUE TITLE
[bug]crash

### ISSUE THREAD

**Issue by H1d3r** [SkyD666/AniVu#61]
当分组中条目数量较大时刷新分组，由于申请的内存不足以换成所有数据，最终导致fc。

建议使用异步刷新读取和加载已缓存的数据。
或者临时调整申请的内存。

```
VersionName: 1.1-beta48
VersionCode: 18
SDK Version: 34
ABI: arm64-v8a

Crash Info: 
java.lang.OutOfMemoryError: Failed to allocate a 18136440 byte allocation with 15565051 free bytes and 14MB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:94)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:113)
	at B7.h.C(SourceFile:52)
	at B7.h.c0(SourceFile:8)
	at A7.b.a(SourceFile:821)
	at D.A.f(SourceFile:130)
	at p7.n.i(SourceFile:97)
	at p7.k.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by SkyD666** [comment]
最新的版本还有这个问题吗？

**Comment by SkyD666** [comment]
> ```
> Crash Info: 
> java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 12728 free bytes and 12KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
> 	at W8.C.<init>(SourceFile:2)
> 	at W8.D.b(SourceFile:45)
> 	at W8.h.c0(SourceFile:40)
> 	at W8.r.L(SourceFile:25)
> 	at W8.q.L(SourceFile:280)
> 	at W8.B.h(SourceFile:23)
> 	at V8.b.a(SourceFile:674)
> 	at A.J.f(SourceFile:130)
> 	at K8.n.h(SourceFile:93)
> 	at K8.k.run(SourceFile:40)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
> 	at java.lang.Thread.run(Thread.java:1012)
> 
> ```
> 还是会fc，可能是我分组订阅的条数比较多

什么版本
