### ISSUE TITLE
软件异常退出

### ISSUE THREAD

**Issue by ACG-Q** [SkyD666/AniVu#93]
错误信息如下：

```
VersionName: 2.0
VersionCode: 19
Brand: Redmi
Model: 22011211C
SDK Version: 33
ABI: arm64-v8a

Crash Info: 
java.lang.RuntimeException: Canvas: trying to draw too large(287777392bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at v0.c.e(SourceFile:93)
	at x0.b.T(SourceFile:34)
	at N0.H.T(SourceFile:25)
	at x0.d.A0(SourceFile:56)
	at A0.a.i(SourceFile:44)
	at A0.b.g(SourceFile:99)
	at n3.u.j(SourceFile:129)
	at n3.u.i(SourceFile:80)
	at A0.b.g(SourceFile:99)
	at n3.m.i(SourceFile:50)
	at A0.b.g(SourceFile:99)
	at n3.t.g(SourceFile:101)
	at N0.H.b(SourceFile:52)
	at N0.d0.U0(SourceFile:55)
	at N0.d0.S0(SourceFile:28)
	at N0.A.l1(SourceFile:6)
	at N0.d0.U0(SourceFile:9)
	at B.p.a(SourceFile:370)
	at m0.r.e(SourceFile:114)
	at m0.u.a(SourceFile:52)
	at m0.v.d(SourceFile:140)
	at N0.l0.a(SourceFile:3)
	at A.K0.j(SourceFile:1239)
	at B.C.n(SourceFile:379)
	at y0.g.x(SourceFile:35)
	at y0.b.e(SourceFile:55)
	at O0.w0.j(SourceFile:137)
	at O0.v.dispatchDraw(SourceFile:100)
	at android.view.View.draw(View.java:23499)
	at android.view.View.updateDisplayListIfDirty(View.java:22308)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4987)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4676)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3873)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2574)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9649)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

**Comment by SkyD666** [comment]
https://github.com/coil-kt/coil/issues/1349

**Comment by SkyD666** [comment]
try this: https://github.com/SkyD666/AniVu/actions/runs/11840989564/artifacts/2188581992

**Comment by ACG-Q** [comment]
> try this: https://github.com/SkyD666/AniVu/actions/runs/11840989564/artifacts/2188581992

目前没有复现
